"""
SentinelScan - FastAPI REST API
=================================
Wraps the SentinelScan scanner as a REST API so it can be called
programmatically from any language, integrated into CI/CD pipelines,
or consumed by a frontend dashboard.

Why FastAPI? (you're learning this now — important for your career)
  - FastAPI is the fastest-growing Python web framework (2023-2026)
  - Used by: Netflix, Uber, Microsoft (Azure Functions), Explosion AI
  - Auto-generates Swagger UI docs at /docs (interactive — no Postman needed)
  - Built-in request/response validation via Pydantic
  - ASYNC support (aiohttp-level performance with sync-friendly interface)
  - Type hints drive everything — you already know types from models.py

What this API exposes:
  POST /scan          — Run a full scan, return results as JSON
  POST /scan/quick    — Run only fast modules (headers, SSL, CORS)
  GET  /health        — Health check for load balancers / uptime monitors
  GET  /              — API info and available endpoints

The /docs endpoint (auto-generated by FastAPI) gives you a full
interactive UI to test the API without writing any frontend code.
Visit http://localhost:8000/docs after starting the server.

Run the server:
  uvicorn api.main:app --reload --port 8000

Learning goals:
  - FastAPI app setup and routing
  - Pydantic schemas for request/response validation
  - Background tasks (FastAPI can run tasks asynchronously)
  - HTTP status codes and proper REST design
"""

import time
from datetime import datetime
from typing import List, Optional

from fastapi import FastAPI, HTTPException, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, HttpUrl, Field

from scanner.core import SentinelCore, normalize_target, validate_target
from scanner.models import Severity


# ─────────────────────────────────────────────────────────────────────────────
#  PYDANTIC SCHEMAS
#  Pydantic is FastAPI's validation library. You define a class that inherits
#  from BaseModel, and FastAPI automatically validates request/response data.
#  Invalid requests get a clear 422 error — no manual validation needed.
# ─────────────────────────────────────────────────────────────────────────────

class ScanRequest(BaseModel):
    """Request body for POST /scan"""
    target: str = Field(
        ...,
        description="Target URL to scan (e.g., https://example.com)",
        example="https://example.com"
    )
    timeout: int = Field(
        default=10,
        ge=3,
        le=30,
        description="Request timeout per module in seconds (3-30)"
    )
    include_threat_intel: bool = Field(
        default=True,
        description="Include Shodan + NVD threat intelligence lookup"
    )
    modules: Optional[List[str]] = Field(
        default=None,
        description="Specific modules to run. Null = all modules.",
        example=["headers", "ssl", "cors"]
    )


class FindingResponse(BaseModel):
    """A single vulnerability finding in the response."""
    title: str
    severity: str
    cvss_score: float
    description: str
    recommendation: str
    evidence: str


class ModuleResponse(BaseModel):
    """Results from one scanner module."""
    module: str
    findings: List[FindingResponse]
    passed_checks: List[str]
    error: str


class ScanSummary(BaseModel):
    """Summary counts of findings by severity."""
    overall_risk: str
    total_findings: int
    critical: int
    high: int
    medium: int
    low: int
    modules_run: List[str]
    scan_duration_seconds: float


class ScanResponse(BaseModel):
    """Complete API response for a scan."""
    sentinelscan_version: str = "1.0"
    target: str
    scan_time: str
    summary: ScanSummary
    modules: List[ModuleResponse]


# ─────────────────────────────────────────────────────────────────────────────
#  FASTAPI APP SETUP
# ─────────────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="SentinelScan API",
    description=(
        "Web security vulnerability scanner API. "
        "Checks targets for security header misconfigurations, SSL/TLS issues, "
        "exposed sensitive files, SQL injection, XSS, CORS misconfigurations, "
        "and enriches results with real CVE data from Shodan and NVD.\n\n"
        "**IMPORTANT:** Only scan systems you own or have written permission to test."
    ),
    version="1.0.0",
    contact={
        "name": "SentinelScan",
        "url": "https://github.com/shree-aru/sentinelscan",
    },
    license_info={
        "name": "MIT",
    }
)

# Allow requests from any origin (required if you build a frontend later)
# In production, restrict this to your frontend's domain
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


# ─────────────────────────────────────────────────────────────────────────────
#  HELPER FUNCTION
# ─────────────────────────────────────────────────────────────────────────────

def report_to_response(report, duration: float) -> ScanResponse:
    """
    Convert a ScanReport object (our internal model) to a ScanResponse
    (Pydantic model for API output). This is the "serialization" step.
    """
    modules_out = []
    for result in report.results:
        findings_out = [
            FindingResponse(
                title=f.title,
                severity=f.severity.value,
                cvss_score=f.cvss_score,
                description=f.description,
                recommendation=f.recommendation,
                evidence=f.evidence
            )
            for f in result.findings
        ]
        modules_out.append(ModuleResponse(
            module=result.module_name,
            findings=findings_out,
            passed_checks=result.passed,
            error=result.error
        ))

    return ScanResponse(
        target=report.target,
        scan_time=report.scan_time,
        summary=ScanSummary(
            overall_risk=report.risk_rating(),
            total_findings=report.total_findings(),
            critical=report.critical_count(),
            high=report.high_count(),
            medium=report.medium_count(),
            low=report.low_count(),
            modules_run=report.modules_run,
            scan_duration_seconds=round(duration, 2)
        ),
        modules=modules_out
    )


# ─────────────────────────────────────────────────────────────────────────────
#  ROUTES
# ─────────────────────────────────────────────────────────────────────────────

@app.get("/", tags=["Info"])
async def root():
    """
    API information and available endpoints.

    This is the landing page of the API — tells clients what's available.
    """
    return {
        "name": "SentinelScan API",
        "version": "1.0.0",
        "description": "Web security vulnerability scanner",
        "endpoints": {
            "POST /scan":         "Run a full security scan",
            "POST /scan/quick":   "Run fast modules only (headers, SSL, CORS)",
            "GET  /health":       "Health check",
            "GET  /docs":         "Interactive API documentation (Swagger UI)",
            "GET  /redoc":        "Alternative API documentation",
        },
        "warning": "Only scan systems you own or have explicit permission to test.",
        "github": "https://github.com/shree-aru/sentinelscan"
    }


@app.get("/health", tags=["Info"])
async def health_check():
    """
    Health check endpoint.

    Load balancers and monitoring tools (Kubernetes, AWS ALB, UptimeRobot)
    call this to verify the service is running. Returns 200 if healthy.
    """
    return {
        "status": "healthy",
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "version": "1.0.0"
    }


@app.post("/scan", response_model=ScanResponse, tags=["Scanner"])
async def run_full_scan(request: ScanRequest):
    """
    Run a complete security scan against the target URL.

    Executes all scanner modules:
    - Security Headers
    - SSL/TLS Certificate
    - Sensitive Files and Directories
    - SQL Injection
    - Reflected XSS
    - CORS Misconfiguration
    - Threat Intelligence (Shodan + NVD CVEs) — if enabled

    Returns a full JSON report with findings, severity ratings, and fix recommendations.

    **Note:** Full scans take 30-120 seconds depending on the target's response time
    and the number of CVEs looked up from NVD.
    """
    # Validate and normalize the target URL
    target = normalize_target(request.target)
    is_valid, error_msg = validate_target(target)

    if not is_valid:
        raise HTTPException(
            status_code=422,
            detail=f"Invalid target URL: {error_msg}"
        )

    start_time = time.time()

    try:
        scanner = SentinelCore(
            timeout=request.timeout,
            include_threat_intel=request.include_threat_intel
        )
        report = scanner.scan(target)
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Scan failed with internal error: {str(e)[:200]}"
        )

    duration = time.time() - start_time
    return report_to_response(report, duration)


@app.post("/scan/quick", response_model=ScanResponse, tags=["Scanner"])
async def run_quick_scan(request: ScanRequest):
    """
    Run a quick scan using only fast, non-injecting modules.

    Modules included:
    - Security Headers (fast — single HTTP request)
    - SSL/TLS Certificate (fast — single TLS handshake)
    - CORS Misconfiguration (fast — 2-3 HTTP requests)

    Modules excluded:
    - SQL Injection (slow — multiple payloads per parameter)
    - XSS (slow — multiple payloads per parameter)
    - Sensitive Files (moderate — 47 HTTP requests)
    - Threat Intelligence (slow — external API calls)

    Typical duration: 3-8 seconds.
    Suitable for: CI/CD pipeline checks, frequent monitoring.
    """
    target = normalize_target(request.target)
    is_valid, error_msg = validate_target(target)

    if not is_valid:
        raise HTTPException(status_code=422, detail=f"Invalid target URL: {error_msg}")

    start_time = time.time()

    try:
        scanner = SentinelCore(
            timeout=request.timeout,
            modules=["headers", "ssl", "cors"],
            include_threat_intel=False
        )
        report = scanner.scan(target)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Scan failed: {str(e)[:200]}")

    duration = time.time() - start_time
    return report_to_response(report, duration)
